// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"empty",
		"kwdVar",
		"=",
		"kwdType",
		"identifier",
		"kwdConst",
		",",
		"||",
		"&&",
		"+",
		"-",
		"*",
		"/",
		"(",
		")",
		"==",
		"!=",
		"<=",
		"<",
		">=",
		">",
		"!",
		"&",
		"intLit",
		"{",
		"}",
		".",
		"[",
		"]",
		"kwdFunc",
		"type",
		"kwdStruct",
		"terminator",
		":",
		"kwdRet",
		"kwdBreak",
		"kwdContinue",
		"kwdGoto",
		"kwdIf",
		"kwdElse",
		"kwdSwitch",
		"kwdCase",
		"kwdDefault",
		"kwdFor",
		"defer",
		"printInt",
		"++",
		"--",
		"assignOp",
		"shortAssign",
		"boolLit",
		"floatLit",
		"kwdImport",
		"kwdPackage",
		"kwdRange",
		"runeLit",
		"stringLit",
	},

	idMap: map[string]Type{
		"INVALID":     0,
		"$":           1,
		"empty":       2,
		"kwdVar":      3,
		"=":           4,
		"kwdType":     5,
		"identifier":  6,
		"kwdConst":    7,
		",":           8,
		"||":          9,
		"&&":          10,
		"+":           11,
		"-":           12,
		"*":           13,
		"/":           14,
		"(":           15,
		")":           16,
		"==":          17,
		"!=":          18,
		"<=":          19,
		"<":           20,
		">=":          21,
		">":           22,
		"!":           23,
		"&":           24,
		"intLit":      25,
		"{":           26,
		"}":           27,
		".":           28,
		"[":           29,
		"]":           30,
		"kwdFunc":     31,
		"type":        32,
		"kwdStruct":   33,
		"terminator":  34,
		":":           35,
		"kwdRet":      36,
		"kwdBreak":    37,
		"kwdContinue": 38,
		"kwdGoto":     39,
		"kwdIf":       40,
		"kwdElse":     41,
		"kwdSwitch":   42,
		"kwdCase":     43,
		"kwdDefault":  44,
		"kwdFor":      45,
		"defer":       46,
		"printInt":    47,
		"++":          48,
		"--":          49,
		"assignOp":    50,
		"shortAssign": 51,
		"boolLit":     52,
		"floatLit":    53,
		"kwdImport":   54,
		"kwdPackage":  55,
		"kwdRange":    56,
		"runeLit":     57,
		"stringLit":   58,
	},
}
