// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	//TODO: refactor to print pos & token string properly
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"empty",
		"kwdVar",
		"=",
		"kwdType",
		"identifier",
		"kwdConst",
		",",
		"||",
		"&&",
		"+",
		"-",
		"*",
		"/",
		"%",
		"(",
		")",
		"==",
		"!=",
		"<=",
		"<",
		">=",
		">",
		"!",
		"&",
		"intLit",
		"{",
		"}",
		".",
		"[",
		"]",
		"kwdFunc",
		"type",
		"kwdStruct",
		"terminator",
		":",
		"kwdRet",
		"kwdBreak",
		"kwdContinue",
		"kwdGoto",
		"kwdIf",
		"kwdElse",
		"kwdSwitch",
		"kwdCase",
		"kwdDefault",
		"kwdFor",
		"defer",
		"printInt",
		"scanInt",
		"++",
		"--",
		"assignOp",
		"shortAssign",
		"boolLit",
		"floatLit",
		"kwdImport",
		"kwdPackage",
		"kwdRange",
		"runeLit",
		"stringLit",
	},

	idMap: map[string]Type{
		"INVALID":     0,
		"$":           1,
		"empty":       2,
		"kwdVar":      3,
		"=":           4,
		"kwdType":     5,
		"identifier":  6,
		"kwdConst":    7,
		",":           8,
		"||":          9,
		"&&":          10,
		"+":           11,
		"-":           12,
		"*":           13,
		"/":           14,
		"%":           15,
		"(":           16,
		")":           17,
		"==":          18,
		"!=":          19,
		"<=":          20,
		"<":           21,
		">=":          22,
		">":           23,
		"!":           24,
		"&":           25,
		"intLit":      26,
		"{":           27,
		"}":           28,
		".":           29,
		"[":           30,
		"]":           31,
		"kwdFunc":     32,
		"type":        33,
		"kwdStruct":   34,
		"terminator":  35,
		":":           36,
		"kwdRet":      37,
		"kwdBreak":    38,
		"kwdContinue": 39,
		"kwdGoto":     40,
		"kwdIf":       41,
		"kwdElse":     42,
		"kwdSwitch":   43,
		"kwdCase":     44,
		"kwdDefault":  45,
		"kwdFor":      46,
		"defer":       47,
		"printInt":    48,
		"scanInt":     49,
		"++":          50,
		"--":          51,
		"assignOp":    52,
		"shortAssign": 53,
		"boolLit":     54,
		"floatLit":    55,
		"kwdImport":   56,
		"kwdPackage":  57,
		"kwdRange":    58,
		"runeLit":     59,
		"stringLit":   60,
	},
}
